<?php

return [

        [
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 2,
            "user_id" => 2,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 3,
            "user_id" => 3,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 4,
            "user_id" => 4,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 5,
            "user_id" => 5,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 6,
            "user_id" => 6,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 7,
            "user_id" => 7,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 8,
            "user_id" => 8,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 9,
            "user_id" => 9,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 10,
            "user_id" => 10,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 11,
            "user_id" => 11,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],    [
            "id" => 12,
            "user_id" => 12,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 13,
            "user_id" => 13,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 14,
            "user_id" => 14,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 15,
            "user_id" => 15,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 16,
            "user_id" => 16,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 17,
            "user_id" => 17,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 18,
            "user_id" => 18,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 19,
            "user_id" => 19,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 20,
            "user_id" => 20,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 21,
            "user_id" => 21,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 22,
            "user_id" => 22,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 23,
            "user_id" => 23,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 24,
            "user_id" => 24,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 25,
            "user_id" => 25,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
];
