<?php

return [

    'apartments' => [
        [
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, CA, 94019, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 100,
            "latitude" => '37°30\'06.0"N',
            "longitude" => '122°28\'06.8"W',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "name" => "The Pacific Dream",
            "address" => "150 Reef Point Rd, Moss Beach, CA, 94038, Stati Uniti",
            "description" => "Il tuo sogno oceanico si manifesta qui.
            Situata ai margini del Pacifico, questa splendida villa è stata progettata e costruita da zero per unirvi alla bellezza e alla pace delle acque circostanti.
            Nuova costruzione completata nel 2020 e arredamento curato professionalmente comprende ogni angolo della villa.",
            "room" => 4,
            "bed" => 6,
            "bathroom" => 4.5,
            "mq" => 300,
            "latitude" => '37°31\'38.9"N',
            "longitude" => '122°30\'59.9"W',
            "visibility" => true,
            "availability" => false,
        ],
        [
            "name" => "Tranquilla casa sull'albero con vista sull'oceano",
            "address" => "340 Swanston St. Aptos, CA, 95003, Stati Uniti",
            "description" => "Presentato da Sunset Magazine come una 'fuga chic'.
            All'interno, i mobili e i dettagli architettonici della metà del secolo sono realizzati con materiali naturali come legno e pietra che creano un tono rilassante e sacro. Rannicchiati con una buona lettura dalla luce che scorre attraverso le finestre dal pavimento al soffitto e sotto le travi di legno svettanti o rimboccati le coperte per la sera chiudendo le porte scorrevoli ispirate agli schermi giapponesi.",
            "room" => 3,
            "bed" => 3,
            "bathroom" => 1,
            "mq" => 120,
            "latitude" => '37°40\'52.6"N',
            "longitude" => '122°29\'04.9"W',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "name" => "Marbella Lane - Oasi costiera rigenerante",
            "address" => "399-307 Genevieve Ave, Pacifica, CA, 94044, Stati Uniti",
            "description" => "Nascosta nella tranquilla e pittoresca valle di Vallemar, questa casa in legno di cedro di Lindahl offre serenità e comodità, con un rapido accesso a molti punti di viaggio. Questa casa ha un elegante design interno dello chalet, l'ampio soggiorno dispone di lucernari e ampie finestre, con accesso diretto alla terrazza del cortile e a una vasca idromassaggio. Goditi una tazza di tè ammirando la miracolosa bellezza della foresta e delle montagne che ti circondano; potresti persino avvistare occasionalmente un cervo o una volpe.",
            "room" => 3,
            "bed" => 4,
            "bathroom" => 3,
            "mq" => 650,
            "latitude" => '37°36\'36.9"N',
            "longitude" => '122°28\'43.1"W',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "name" => "Alloggio di lusso a Del Monte Forest, California, Stati Uniti",
            "address" => "3100-3198 Patio Dr, Pebble Beach, CA, 93953, Stati Uniti",
            "description" => "La foresta di Del Monte ispira la forma di questa residenza contemporanea californiana. Una capanna all'aperto riecheggia le linee rette degli alberi più alti, l'area lounge si estende sotto i rami tortuosi e, all'interno, danze luminose soffuse con le foglie su un tappeto verde muschio e pannelli in legno. 3 campi da golf, tra cui Pebble Beach, e 2 spiagge in 10 minuti ti faranno prendere il via e la sabbia.",
            "room" => 3,
            "bed" => 3,
            "bathroom" => 3,
            "mq" => 800,
            "latitude" => '36°35\'29.3"N',
            "longitude" => '121°57\'12.1"W',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "name" => "Luminoso, moderno 5b/4ba Portola Valley Home",
            "address" => "144-160 Los Trancos Cir, Portola Valley, CA, 94028, Stati Uniti",
            "description" => "Casa spaziosa e tranquilla nella Valle di Portola. Goditi la vasta terrazza all'aperto, accomodati vicino al camino, ammira gli alberi imponenti attraverso le splendide finestre panoramiche della casa o semplicemente rilassati nello spazio pulito, moderno e completamente arredato. I rinomati sentieri di Portola Valley che si affacciano sulla baia di San Francisco si trovano a soli 100 passi di distanza.",
            "room" => 5,
            "bed" => 5,
            "bathroom" => 4,
            "mq" => 350,
            "latitude" => '122°11\'57.3"W',
            "longitude" => '37°20\'49.5"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "name" => "Nature/Architectural Lovers Dream Pad in Sequoie",
            "address" => "999-731 Lovell Ave, Mill Valley, CA, 94941, Stati Uniti",
            "description" => "Siamo amanti della natura e abbiamo comprato la casa dei nostri sogni tra le sequoie ai piedi del Monte Tam e ora lo condividiamo con i viaggiatori che apprezzano l'architettura e lo stile di vita all'interno e all'esterno della California settentrionale! Costruita dal visionario architetto biologico Daniel Lieberman nel 1962 su sequoie e vetri secolari, la casa è una composizione piena di spazi aperti ancorati a un camino centrale, simile al lavoro del mentore di Lieberman, Frank Lloyd Wright.",
            "room" => 3,
            "bed" => 2,
            "bathroom" => 3.5,
            "mq" => 280,
            "latitude" => '122°33\'57.9"W',
            "longitude" => '37°54\'48.3"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "name" => "Rifugio esecutivo nel cuore della Silicon Valley",
            "address" => "3562 Golden State Dr, Santa Clara, CA, 95051, Stati Uniti",
            "description" => "Gioca e lavora in questo splendido rambler di 2100 metri quadrati a pochi minuti da Big Tech, Levi Stadium, Great America e tutto ciò che c'è di fantastico nella Bay Area. Master suite, più 2 camere da letto e un ufficio con 2 postazioni di lavoro e un futon per 8 persone. Goditi la cucina gourmet mentre ascolti la tua stazione Spotify preferita sul sistema di intrattenimento utilizzando l'app Onkyo. LG 55 in schermo piatto e camino fuori dalla cucina. Patio anteriore per il caffè del mattino e vasca idromassaggio per rilassarsi. Custode in loco nell'unità collegata.",
            "room" => 4,
            "bed" => 4,
            "bathroom" => 2,
            "mq" => 2100,
            "latitude" => '121°59\'39.0"W',
            "longitude" => '37°20\'36.9"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "name" => "Il cavalluccio marino di Willow Glen",
            "address" => "2541-2579 Richland Ave, San Jose, CA, 95125, Stati Uniti",
            "description" => "In primo piano su Houzz, Style Me Pretty Living e PopSugar, oltre che selezionato per il prestigioso Willow Glen Home Tour, questa casa pluripremiata completamente ristrutturata con un paradiso per il nuoto è stata aperta per le tue vacanze, soggiorni o viaggi di lavoro!
            Dalla scintillante piscina e spa a forma di cavalluccio marino, al pavimento del bagno fatto di pochi centesimi, l'unicità, il comfort e la gioia di questa casa ti lascerà sicuramente sorridente.
            Willow Glen, San Jose è vicino a negozi, cibo e autostrade.",
            "room" => 3,
            "bed" => 4,
            "bathroom" => 2.5,
            "mq" => 500,
            "latitude" => '121°53\'12.1"W',
            "longitude" => '37°16\'57.1"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "name" => "Log-Cabin Home Retreat nella foresta",
            "address" => "123 Skylonda Dr, Woodside, CA, 94062, Stati Uniti",
            "description" => "Rilassati e rigenerati in questo incantevole rifugio unico nel suo genere in legno, situato su un ettaro di sequoie della California del Nord. Costruito nel 1937, questo luogo ospita matrimoni, concerti all'aperto, ritiri, famiglie e gruppi che hanno apprezzato la proprietà per decenni. Vuoi fare escursioni a piedi o in bicicletta? La proprietà ha un sentiero che inizia in fondo al vialetto, va dietro la casa e conduce alla riserva aperta La Honda Creek Open Space Preserve di oltre 6100 acri. ",
            "room" => 3,
            "bed" => 6,
            "bathroom" => 2,
            "mq" => 600,
            "latitude" => '122°15\'58.7"W',
            "longitude" => '37°23\'06.2"N',
            "visibility" => true,
            "availability" => false,
        ],
        [
            "name" => "Splendido resort californiano e piscina a sfioro",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],    [
            "id" => 12,
            "user_id" => 12,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 13,
            "user_id" => 13,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 14,
            "user_id" => 14,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 15,
            "user_id" => 15,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 16,
            "user_id" => 16,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 17,
            "user_id" => 17,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 18,
            "user_id" => 18,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 19,
            "user_id" => 19,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 20,
            "user_id" => 20,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 21,
            "user_id" => 21,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 22,
            "user_id" => 22,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 23,
            "user_id" => 23,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 24,
            "user_id" => 24,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ],
        [
            "id" => 25,
            "user_id" => 25,
            "name" => "Tenuta costiera con vasca idromassaggio e vista sull'oceano",
            "address" => "590 Ave Alhambra, Half Moon Bay, 94019, CA, Stati Uniti",
            "description" => "Raggiungi a piedi le migliori spiagge statali della zona, i ristoranti premiati, il porto di Half Moon Bay, le escursioni a piedi lungo il California Coastal Trail, le attività per famiglie nella zona e molto altro ancora.",
            "room" => 3,
            "bed" => 9,
            "bathroom" => 2,
            "mq" => 3,
            "latitude" => '122°28\'06.8"W',
            "longitude" => '37°30\'06.0"N',
            "visibility" => true,
            "availability" => true,
        ]
    ],

    // SERVIZI DEGLI APPARTAMENTI

    'services' => [
        [
            'name' => 'Cucina',
            'description' => 'Uno spazio in cui gli ospiti possono cucinare',
            'icon' => 'fa-kitchen-set',
        ],
        [
            'name' => 'Fornelli',
            'description' => 'Fornelli a induzione',
            'icon' => 'fa-fire-burner',
        ],
        [
            'name' => 'Servizio',
            'description' => '',
            'icon' => 'fa-plane-up',
        ],
        [
            'name' => 'Posate',
            'description' => '',
            'icon' => 'a-utensils',
        ],
        [
            'name' => 'caffè',
            'description' => 'macchina per caffè espresso',
            'icon' => 'fa-mug-saucer',
        ],
        [
            'name' => 'colazione',
            'description' => 'colazione alle 10.00',
            'icon' => 'fa-mug-saucer',
        ],
        [
            'name' => 'Frigorifero',
            'description' => '',
            'icon' => 'fa-toilet-portable',
        ],
        [
            'name' => 'Ingresso privato',
            'description' => 'Ingresso separato su strada o edificio',
            'icon' => 'fa-door-closed',
        ],
        [
            'name' => 'escursioni',
            'description' => '',
            'icon' => 'fa-person-hiking',
        ],
        [
            'name' => 'campeggio',
            'description' => '',
            'icon' => 'fa-campground',
        ],
        [
            'name' => 'Taxi',
            'description' => 'Servizio Taxi',
            'icon' => 'fa-taxi',
        ],
        [
            'name' => 'Tram',
            'description' => '',
            'icon' => 'fa-train-subway',
        ],
        [
            'name' => 'Autobus',
            'description' => 'Autobus a trecento metri dall\'abitazione',
            'icon' => 'fa-bus',
        ],
        [
            'name' => 'Stampante',
            'description' => 'Stampante a colori',
            'icon' => 'fa-print',
        ],
        [
            'name' => 'Animali domestici ammessi',
            'description' => 'Gli animali di servizio sono sempre ammessi',
            'icon' => 'fa-paw',
        ],
        [
            'name' => 'Self check-in',
            'description' => '',
            'icon' => 'fa-key',
        ],
        [
            'name' => 'TV',
            'description' => '',
            'icon' => 'fa-tv',
        ],
        [
            'name' => 'Aria condizionata',
            'description' => '',
            'icon' => 'fa-fan',
        ],
        [
            'name' => 'Essenziali',
            'description' => 'Asciugamani, lenzuola, sapone e carta igienica',
            'icon' => 'fa-pump-soap',
        ],
    ],

    //sponsors degli appartamenti

    'sponsors' => [
        [
            'name' => 'Economy',
            'price' => 2.99,
            'duration' => 1,
        ],
        [
            'name' => 'Standard',
            'price' => 4.99,
            'duration' => 3,
        ],
        [
            'name' => 'Premium',
            'price' => 8.99,
            'duration' => 6,
        ],
    ],

    // TomTom API

    'TomTomAPI' => [
        'apiUrl' => 'https://api.tomtom.com/geocode/'
    ]
];
